### ISSUE TITLE
Nombre de participant a un event ? 

### ISSUE THREAD

**Issue by jibe0123** [Bunkermaster/attendance-assignment#3]
Il serait sympa de pouvoir rajouté une table pour stocké les participants a un event.
On pourrait grace a cette table généré des statistiques comme : 
- Pourcentage de remplissage des 'Events'
- Quelle sont les users les plus en retards, absents etc..
- Et surtout utiliser les données pour l'apprentissage machine.

De plus lorsque l'utilisateur aura scanner avec réussite son qr code, on change le statut du participant.

# Participant
    Id int
    User_id int (FK)
    Event_id int (FK)
    statut int

**Comment by Bunkermaster** [comment]
Ça n'impact aucunement l'API. Choisissez une solution qui permettra d'implémenter les fonctionnalités listées.
