### ISSUE TITLE
Refresh Token: Expiration Time

### ISSUE THREAD

**Issue by KylianLM** [Bunkermaster/attendance-assignment#4]
Quel est le temps de vie du token retournée par l'authentification ?

https://github.com/Bunkermaster/attendance-assignment#post-apilogin

**Comment by jibe0123** [comment]
30 secondes ?
https://github.com/Bunkermaster/attendance-assignment#input-4

**Comment by KylianLM** [comment]
Il me semble que c'est la durée de vie des QRCode et non du token de connexion

**Comment by jibe0123** [comment]
Ah oui effectivement ...

**Comment by Bunkermaster** [comment]
OSEF
