### ISSUE TITLE
Système de Token

### ISSUE THREAD

**Issue by Psyker** [Bunkermaster/attendance-assignment#6]
Pour le système de Token, on a juste besoin d'avoir une connexion de l'appli à l'api donc y a t-il besoin d'avoir autant de users que d'élèves potentiel ou juste un user représentant l'appli mobile ? 

Et on checkera juste que les calls à l'api proviennent bien de l'appli mobile ?
Doit-on gérer l'inscription également ?

**Comment by Bunkermaster** [comment]
Voir v0.2 pour users de test par défaut à implémenter
